//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrinterInfo.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrinterInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!DOCTYPE PRINTER
        ///	[
        ///		&lt;!ELEMENT PRINTER (NAME, MODEL, DEPARTMENT, IPV4, MAC, SERIAL, INVENTARY)&gt;
        ///		&lt;!ELEMENT NAME (#PCDATA)&gt;
        ///		&lt;!ELEMENT MODEL (#PCDATA)&gt;
        ///		&lt;!ELEMENT DEPARTMENT (#PCDATA)&gt;
        ///		&lt;!ELEMENT IPV4 (#PCDATA)&gt;
        ///		&lt;!ELEMENT MAC (#PCDATA)&gt;
        ///		&lt;!ELEMENT SERIAL (#PCDATA)&gt;
        ///		&lt;!ELEMENT INVENTARY (#PCDATA)&gt;
        ///	]
        ///&gt;
        ///&lt;!--File name: printerList.xml --&gt;
        ///&lt;data&gt;
        /// &lt;printer number=&quot;1&quot;&gt;
        ///    &lt;NAME&gt;Hello&lt;/NAME&gt;
        ///	&lt;MODEL&gt;HP LaserJet 4350&lt;/MODEL&gt;
        ///    &lt;DEPARTMENT&gt;Dear &lt;/ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string printerList {
            get {
                return ResourceManager.GetString("printerList", resourceCulture);
            }
        }
    }
}
